/**
 * Starting dataset. This exists only so a fresh install has something to render —
 * the storefront reads everything from MongoDB, so deleting this changes nothing
 * structurally. Images point at Unsplash; replace them from the admin panel and
 * they will be served from your own Cloudinary account.
 */

const img = (id, alt) => ({
  url: `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`,
  publicId: `seed/${id}`,
  alt,
});

const categories = [
  {
    name: 'Building Materials',
    image: img('1504148455328-c376907d081c', 'Stacked plywood sheets'),
    description: 'Plywood, laminates, boards and everything that goes into a structure.',
    displayOrder: 1,
    isFeatured: true,
    subCategories: ['Plywood', 'Laminates', 'MDF & HDF Boards', 'Cement & Aggregates'],
  },
  {
    name: 'Hardware & Fittings',
    image: img('1581092160562-40aa08e78837', 'Cabinet hinge hardware'),
    description: 'Hinges, channels, locks and fasteners for every joinery job.',
    displayOrder: 2,
    isFeatured: true,
    subCategories: ['Hinges', 'Drawer Channels', 'Locks & Latches', 'Screws & Fasteners'],
  },
  {
    name: 'Paints & Finishes',
    image: img('1562259949-e8e7689d7828', 'Paint rollers and colour swatches'),
    description: 'Interior, exterior and wood finishes from trusted brands.',
    displayOrder: 3,
    isFeatured: true,
    subCategories: ['Interior Paint', 'Exterior Paint', 'Wood Polish', 'Primers'],
  },
  {
    name: 'Power Tools',
    image: img('1581147036324-c1c9b9d8b3f9', 'Power tools on a workbench'),
    description: 'Drills, saws, grinders and the accessories that keep them running.',
    displayOrder: 4,
    isFeatured: true,
    subCategories: ['Drills', 'Saws', 'Grinders', 'Tool Accessories'],
  },
  {
    name: 'Electricals',
    image: img('1621905251189-08b45d6a269e', 'Electrical wiring'),
    description: 'Wires, switches, lighting and modular accessories.',
    displayOrder: 5,
    subCategories: ['Wires & Cables', 'Switches & Sockets', 'LED Lighting', 'MCB & Distribution'],
  },
  {
    name: 'Sanitary & Plumbing',
    image: img('1584622650111-993a426fbf0a', 'Modern bathroom faucet'),
    description: 'Pipes, fittings, faucets and bathroom fixtures.',
    displayOrder: 6,
    subCategories: ['Pipes & Fittings', 'Faucets', 'Sanitaryware', 'Water Tanks'],
  },
];

/**
 * Brand catalogue. The names have to match `products[].brand` exactly — that string
 * is what the storefront filters on, and the catalogue is what gives it a logo.
 */
const brands = [
  {
    name: 'TimberCore',
    description: 'Marine-grade plywood and engineered boards for structural joinery.',
    logo: img('1504148455328-c376907d081c', 'TimberCore'),
    displayOrder: 1,
    isFeatured: true,
  },
  {
    name: 'SurfaceOne',
    description: 'Decorative laminates and surface finishes for furniture and interiors.',
    logo: img('1600566753086-00f18fb6b3ea', 'SurfaceOne'),
    displayOrder: 2,
    isFeatured: true,
  },
  {
    name: 'FitPro',
    description: 'Hinges, channels and cabinet hardware built for daily-use cycles.',
    logo: img('1581092160562-40aa08e78837', 'FitPro'),
    displayOrder: 3,
    isFeatured: true,
  },
  {
    name: 'ChromaPro',
    description: 'Interior, exterior and wood-finish paint systems.',
    logo: img('1589939705384-5185137a7f0f', 'ChromaPro'),
    displayOrder: 4,
    isFeatured: true,
  },
  {
    name: 'ForgeTech',
    description: 'Trade-grade power tools and accessories with a 2 year warranty.',
    logo: img('1572981779307-38b8cabb2407', 'ForgeTech'),
    displayOrder: 5,
    isFeatured: true,
  },
  {
    name: 'VoltLine',
    description: 'Wires, switches, modular accessories and LED lighting.',
    logo: img('1565814329452-e1efa11c5b89', 'VoltLine'),
    displayOrder: 6,
  },
  {
    name: 'AquaForm',
    description: 'Pipes, fittings, faucets and sanitaryware for wet areas.',
    logo: img('1584622650111-993a426fbf0a', 'AquaForm'),
    displayOrder: 7,
  },
];

const banners = [
  {
    title: 'Build Better. Build Premium.',
    subtitle: 'Up to 45% off on marine-grade plywood and laminates this season.',
    ctaLabel: 'Shop Building Materials',
    ctaLink: '/products?category=building-materials',
    image: img('1503387762-592deb58ef4e', 'Construction site'),
    placement: 'hero',
    theme: 'dark',
    displayOrder: 1,
  },
  {
    title: 'Professional Power Tools',
    subtitle: 'Trade-grade drills, saws and grinders with 2 year warranty.',
    ctaLabel: 'Explore Tools',
    ctaLink: '/products?category=power-tools',
    image: img('1581147036324-c1c9b9d8b3f9', 'Power tools on a workbench'),
    placement: 'hero',
    theme: 'dark',
    displayOrder: 2,
  },
  {
    title: 'Colour Your Space',
    subtitle: 'Premium interior emulsions starting at ₹389 per litre.',
    ctaLabel: 'Browse Paints',
    ctaLink: '/products?category=paints-finishes',
    image: img('1562259949-e8e7689d7828', 'Paint rollers and colour swatches'),
    placement: 'hero',
    theme: 'dark',
    displayOrder: 3,
  },
];

const coupons = [
  {
    code: 'WELCOME10',
    description: '10% off on your first order',
    discountType: 'percentage',
    discountValue: 10,
    maxDiscountAmount: 500,
    minOrderAmount: 999,
    perUserLimit: 1,
    expiresAt: new Date(Date.now() + 180 * 86400000),
  },
  {
    code: 'FLAT250',
    description: 'Flat ₹250 off on orders above ₹2499',
    discountType: 'flat',
    discountValue: 250,
    minOrderAmount: 2499,
    perUserLimit: 3,
    expiresAt: new Date(Date.now() + 90 * 86400000),
  },
  {
    code: 'BULK15',
    description: '15% off on orders above ₹9999',
    discountType: 'percentage',
    discountValue: 15,
    maxDiscountAmount: 2500,
    minOrderAmount: 9999,
    perUserLimit: 5,
    expiresAt: new Date(Date.now() + 120 * 86400000),
  },
];

/**
 * Products reference their category/sub-category by name; the seeder resolves them
 * to ObjectIds after the taxonomy is created.
 */
const products = [
  {
    name: 'MarineGrade 710 Waterproof Plywood — 19mm',
    brand: 'TimberCore',
    category: 'Building Materials',
    subCategory: 'Plywood',
    price: 4250,
    discountPercent: 22,
    stock: 140,
    shortDescription: 'BWP grade boiling-water-proof plywood with a lifetime warranty against borers and termites.',
    description: `<p><strong>MarineGrade 710</strong> is a boiling water proof (BWP) plywood manufactured to IS:710 standards, built for kitchens, bathrooms and any surface that meets moisture daily.</p>
<p>Each sheet is pressed from 100% hardwood veneers with a phenol formaldehyde resin bond, then chemically treated end-to-end so borers and termites never get a foothold. The calibrated surface takes laminate, veneer and polish evenly, with no telegraphing after finishing.</p>
<ul><li>Zero core gaps — verified sheet by sheet</li><li>Dimensionally stable across humidity swings</li><li>Lifetime warranty against borer and termite damage</li></ul>`,
    highlights: [
      'IS:710 certified boiling water proof grade',
      '100% hardwood core with zero gaps',
      'Lifetime borer and termite warranty',
      'Calibrated surface, ready for lamination',
    ],
    features: [
      { key: 'Material', value: '100% Hardwood Veneer' },
      { key: 'Thickness', value: '19 mm' },
      { key: 'Standard', value: 'IS:710 (BWP Grade)' },
      { key: 'Sheet Size', value: '8 ft × 4 ft (2440 × 1220 mm)' },
      { key: 'Finish', value: 'Calibrated / Sanded Both Sides' },
      { key: 'Bonding', value: 'Phenol Formaldehyde (PF) Resin' },
      { key: 'Density', value: '700-720 kg/m³' },
      { key: 'Applications', value: 'Modular Kitchens, Wardrobes, Bathroom Vanities, Marine Interiors' },
      { key: 'Warranty', value: 'Lifetime against borer & termite' },
    ],
    faqs: [
      { question: 'Can this be used outdoors?', answer: 'Yes. BWP grade withstands prolonged moisture, but exposed exterior surfaces should still be sealed with an exterior-grade finish for UV protection.' },
      { question: 'Does the price include cutting?', answer: 'Full sheets are shipped uncut. Custom cutting can be requested in the order notes and is quoted separately.' },
      { question: 'How is delivery handled for full sheets?', answer: 'Sheets ship flat on a pallet via surface freight. Delivery typically takes 4-7 working days depending on the pincode.' },
    ],
    images: [img('1504148455328-c376907d081c', 'Stacked plywood sheets'), img('1416339306562-f3d12fefd36f', 'Plywood edge detail')],
    tags: ['plywood', 'waterproof', 'bwp', 'marine'],
    isFeatured: true,
    isTopSelling: true,
  },
  {
    name: 'HighGloss Decorative Laminate 1mm — Walnut Oak',
    brand: 'SurfaceOne',
    category: 'Building Materials',
    subCategory: 'Laminates',
    price: 1890,
    discountPercent: 30,
    stock: 220,
    shortDescription: 'Scratch-resistant high gloss laminate with a true-to-grain walnut oak print.',
    description: `<p>A 1mm decorative laminate finished to a mirror gloss, engineered for wardrobe shutters, kitchen fronts and feature panels where the surface is the statement.</p>
<p>The print layer is UV-cured for colour stability, and the overlay resists everyday scuffing, staining and heat from routine kitchen use.</p>`,
    highlights: ['Mirror-grade high gloss finish', 'UV-cured, fade-resistant print', 'Scratch and stain resistant overlay'],
    features: [
      { key: 'Material', value: 'Decorative High Pressure Laminate' },
      { key: 'Thickness', value: '1 mm' },
      { key: 'Standard', value: 'IS:2046 Type S' },
      { key: 'Sheet Size', value: '8 ft × 4 ft' },
      { key: 'Finish', value: 'High Gloss' },
      { key: 'Shade', value: 'Walnut Oak' },
      { key: 'Applications', value: 'Wardrobe Shutters, Kitchen Fronts, Wall Panels' },
    ],
    images: [img('1600566753086-00f18fb6b3ea', 'Laminate wood texture')],
    tags: ['laminate', 'gloss', 'walnut'],
    isFeatured: true,
  },
  {
    name: 'SoftClose Hydraulic Cabinet Hinge — Full Overlay (Pack of 10)',
    brand: 'FitPro',
    category: 'Hardware & Fittings',
    subCategory: 'Hinges',
    price: 1450,
    discountPercent: 35,
    stock: 380,
    shortDescription: 'Nickel-plated hydraulic hinges rated for 60,000 open-close cycles.',
    description: `<p>Hydraulic soft-close hinges that stop the slam without a separate damper. The integrated oil cylinder decelerates the shutter over the last 30 degrees for a silent, controlled close every time.</p>
<p>Three-way adjustment lets you correct depth, height and side alignment after installation without removing the shutter.</p>`,
    highlights: ['60,000 cycle tested', 'Three-way post-fit adjustment', 'Nickel-plated, rust resistant'],
    features: [
      { key: 'Material', value: 'Cold Rolled Steel, Nickel Plated' },
      { key: 'Type', value: 'Full Overlay, Clip-On' },
      { key: 'Opening Angle', value: '110°' },
      { key: 'Cup Diameter', value: '35 mm' },
      { key: 'Cycle Rating', value: '60,000 cycles' },
      { key: 'Adjustment', value: '3-way (depth, height, side)' },
      { key: 'Pack Size', value: '10 pieces' },
      { key: 'Applications', value: 'Kitchen Cabinets, Wardrobes, Vanity Units' },
    ],
    images: [img('1581092160562-40aa08e78837', 'Cabinet hinge hardware')],
    tags: ['hinge', 'soft close', 'hardware'],
    isTopSelling: true,
  },
  {
    name: 'Telescopic Ball Bearing Drawer Channel 18" (Pair)',
    brand: 'FitPro',
    category: 'Hardware & Fittings',
    subCategory: 'Drawer Channels',
    price: 890,
    discountPercent: 25,
    stock: 260,
    shortDescription: 'Full-extension ball bearing slides with a 45kg dynamic load rating.',
    description: `<p>Full-extension telescopic slides that bring the entire drawer clear of the carcass, so nothing gets lost at the back. Precision ball bearings keep the travel smooth even under load.</p>`,
    highlights: ['Full extension travel', '45 kg dynamic load', 'Zinc plated anti-corrosion finish'],
    features: [
      { key: 'Material', value: 'Cold Rolled Steel, Zinc Plated' },
      { key: 'Length', value: '18 inch (450 mm)' },
      { key: 'Extension', value: 'Full Extension' },
      { key: 'Load Capacity', value: '45 kg (dynamic)' },
      { key: 'Bearing', value: 'Precision Ball Bearing' },
      { key: 'Applications', value: 'Kitchen Drawers, Office Furniture, Storage Units' },
    ],
    images: [img('1558618666-fcd25c85cd64', 'Drawer slide hardware')],
    tags: ['drawer', 'channel', 'slide'],
  },
  {
    name: 'PremiumShield Interior Emulsion — 20L (Ivory White)',
    brand: 'ChromaPro',
    category: 'Paints & Finishes',
    subCategory: 'Interior Paint',
    price: 8990,
    discountPercent: 18,
    stock: 75,
    shortDescription: 'Low-VOC washable interior emulsion with a soft sheen finish.',
    description: `<p>A premium acrylic emulsion formulated for interior walls and ceilings, delivering a smooth soft-sheen finish that stays washable for years.</p>
<p>Low VOC and virtually odourless, so rooms are usable again within hours of the final coat.</p>`,
    highlights: ['Washable, stain-resistant film', 'Low VOC and low odour', 'Covers up to 140 sq ft per litre per coat'],
    features: [
      { key: 'Type', value: 'Acrylic Emulsion' },
      { key: 'Volume', value: '20 Litres' },
      { key: 'Finish', value: 'Soft Sheen' },
      { key: 'Shade', value: 'Ivory White' },
      { key: 'Coverage', value: '130-140 sq ft / litre / coat' },
      { key: 'Drying Time', value: '30 min surface dry, 4 hr recoat' },
      { key: 'VOC Content', value: '< 50 g/L' },
      { key: 'Applications', value: 'Interior Walls, Ceilings, Plastered Surfaces' },
    ],
    images: [img('1589939705384-5185137a7f0f', 'Paint bucket and roller')],
    tags: ['paint', 'emulsion', 'interior'],
    isFeatured: true,
  },
  {
    name: '13mm Impact Drill Machine 750W with 100-Piece Accessory Kit',
    brand: 'ForgeTech',
    category: 'Power Tools',
    subCategory: 'Drills',
    price: 4499,
    discountPercent: 40,
    stock: 95,
    shortDescription: 'Reversible variable-speed impact drill with a full bit and accessory kit.',
    description: `<p>A 750W impact drill that handles concrete, masonry, wood and steel out of one chuck. Variable speed with a lock-on trigger and full reverse for driving and extraction.</p>
<p>Ships with a 100-piece kit covering masonry, HSS and wood bits plus screwdriver bits and sockets.</p>`,
    highlights: ['750W copper-wound motor', 'Variable speed with forward/reverse', '100-piece accessory kit included', '2 year warranty'],
    features: [
      { key: 'Power', value: '750 W' },
      { key: 'Chuck Capacity', value: '13 mm' },
      { key: 'No Load Speed', value: '0-2800 RPM' },
      { key: 'Impact Rate', value: '0-44,800 BPM' },
      { key: 'Modes', value: 'Drill / Impact Drill' },
      { key: 'Cable Length', value: '2 metres' },
      { key: 'Warranty', value: '2 Years' },
      { key: 'Applications', value: 'Concrete, Masonry, Wood, Metal' },
    ],
    images: [img('1572981779307-38b8cabb2407', 'Power drill'), img('1504148455328-c376907d081c', 'Tools flat lay')],
    tags: ['drill', 'power tool', 'impact'],
    isFeatured: true,
    isTopSelling: true,
  },
  {
    name: 'FR Copper Wire 2.5 sq mm — 90m Coil',
    brand: 'VoltLine',
    category: 'Electricals',
    subCategory: 'Wires & Cables',
    price: 2650,
    discountPercent: 15,
    stock: 190,
    shortDescription: 'ISI-marked flame-retardant copper wire for domestic power circuits.',
    description: `<p>99.97% electrolytic-grade bare copper conductor with FR PVC insulation, rated for the power circuits in domestic and light commercial wiring.</p>`,
    highlights: ['99.97% electrolytic grade copper', 'Flame retardant PVC insulation', 'ISI marked to IS:694'],
    features: [
      { key: 'Conductor', value: '99.97% Electrolytic Grade Copper' },
      { key: 'Cross Section', value: '2.5 sq mm' },
      { key: 'Length', value: '90 metres' },
      { key: 'Insulation', value: 'FR PVC' },
      { key: 'Voltage Rating', value: '1100 V' },
      { key: 'Standard', value: 'IS:694' },
      { key: 'Applications', value: 'Power Sockets, AC Circuits, Domestic Wiring' },
    ],
    images: [img('1621905251189-08b45d6a269e', 'Electrical wiring')],
    tags: ['wire', 'copper', 'electrical'],
    isTopSelling: true,
  },
  {
    name: 'Single Lever Basin Mixer — Brushed Chrome',
    brand: 'AquaForm',
    category: 'Sanitary & Plumbing',
    subCategory: 'Faucets',
    price: 3450,
    discountPercent: 28,
    stock: 110,
    shortDescription: 'Solid brass basin mixer with a ceramic cartridge and aerated flow.',
    description: `<p>A forged brass basin mixer finished in brushed chrome, built around a 35mm ceramic disc cartridge rated for 500,000 cycles.</p>
<p>The aerator holds flow at a comfortable 6 litres per minute, cutting water use without the pressure dropping off.</p>`,
    highlights: ['Forged brass body', '35mm ceramic disc cartridge', 'Water-saving aerator', '10 year warranty on cartridge'],
    features: [
      { key: 'Material', value: 'Forged Brass' },
      { key: 'Finish', value: 'Brushed Chrome' },
      { key: 'Cartridge', value: '35 mm Ceramic Disc' },
      { key: 'Flow Rate', value: '6 L/min (aerated)' },
      { key: 'Working Pressure', value: '0.5 - 5 bar' },
      { key: 'Installation', value: 'Single Hole Deck Mounted' },
      { key: 'Warranty', value: '10 Years (cartridge)' },
      { key: 'Applications', value: 'Wash Basins, Vanity Counters' },
    ],
    images: [img('1584622650111-993a426fbf0a', 'Modern bathroom faucet')],
    tags: ['faucet', 'basin', 'mixer'],
    isFeatured: true,
  },
  {
    name: '18mm Pre-Laminated MDF Board — Frosty White (8×4)',
    brand: 'TimberCore',
    category: 'Building Materials',
    subCategory: 'MDF & HDF Boards',
    price: 2290,
    discountPercent: 20,
    stock: 160,
    shortDescription: 'Double-sided pre-laminated MDF with a uniform, screw-friendly core.',
    description: `<p>Pre-laminated medium density fibreboard finished both sides, saving a full lamination step on shutters, partitions and modular carcasses.</p>`,
    highlights: ['Pre-laminated both sides', 'Uniform, void-free core', 'Excellent screw holding'],
    features: [
      { key: 'Material', value: 'Medium Density Fibreboard' },
      { key: 'Thickness', value: '18 mm' },
      { key: 'Sheet Size', value: '8 ft × 4 ft' },
      { key: 'Finish', value: 'Pre-Laminated Both Sides' },
      { key: 'Shade', value: 'Frosty White' },
      { key: 'Density', value: '750 kg/m³' },
      { key: 'Applications', value: 'Modular Furniture, Partitions, Shutters' },
    ],
    images: [img('1600607687939-ce8a6c25118c', 'White board panels')],
    tags: ['mdf', 'board', 'prelam'],
  },
  {
    name: '9W LED Panel Downlight — Cool White (Pack of 6)',
    brand: 'VoltLine',
    category: 'Electricals',
    subCategory: 'LED Lighting',
    price: 1740,
    discountPercent: 32,
    stock: 300,
    shortDescription: 'Slim recessed LED panels with a 2-year replacement warranty.',
    description: `<p>Slim recessed LED downlights with a diffused lens for even, glare-free light. Wide input range keeps output stable through voltage fluctuation.</p>`,
    highlights: ['900 lumen output per unit', '100-265V wide input range', '2 year replacement warranty'],
    features: [
      { key: 'Wattage', value: '9 W' },
      { key: 'Colour Temperature', value: '6500K Cool White' },
      { key: 'Luminous Flux', value: '900 lm' },
      { key: 'Input Voltage', value: '100-265 V AC' },
      { key: 'Cut-out Size', value: '105 mm' },
      { key: 'Pack Size', value: '6 pieces' },
      { key: 'Life', value: '25,000 hours' },
      { key: 'Applications', value: 'False Ceilings, Corridors, Retail Lighting' },
    ],
    images: [img('1565814329452-e1efa11c5b89', 'Ceiling LED lights')],
    tags: ['led', 'light', 'downlight'],
    isTopSelling: true,
  },
  {
    name: '4 Inch Angle Grinder 850W with Guard',
    brand: 'ForgeTech',
    category: 'Power Tools',
    subCategory: 'Grinders',
    price: 3299,
    discountPercent: 27,
    stock: 85,
    shortDescription: 'Compact 850W grinder with anti-vibration handle and spindle lock.',
    description: `<p>An 850W angle grinder sized for cutting, grinding and polishing in tight spaces, with a tool-free adjustable guard and spindle lock for quick disc changes.</p>`,
    highlights: ['850W high-torque motor', 'Tool-free guard adjustment', 'Anti-vibration side handle'],
    features: [
      { key: 'Power', value: '850 W' },
      { key: 'Disc Diameter', value: '100 mm (4 inch)' },
      { key: 'No Load Speed', value: '11,000 RPM' },
      { key: 'Spindle Thread', value: 'M10' },
      { key: 'Weight', value: '1.9 kg' },
      { key: 'Warranty', value: '2 Years' },
      { key: 'Applications', value: 'Metal Cutting, Grinding, Surface Prep, Tile Cutting' },
    ],
    images: [img('1530124566582-a618bc2615dc', 'Angle grinder tool')],
    tags: ['grinder', 'power tool'],
  },
  {
    name: 'CPVC Plumbing Pipe 1 Inch — 3m Length',
    brand: 'AquaForm',
    category: 'Sanitary & Plumbing',
    subCategory: 'Pipes & Fittings',
    price: 640,
    discountPercent: 12,
    stock: 420,
    shortDescription: 'Hot and cold water CPVC pipe rated to 93°C.',
    description: `<p>CPVC pipe engineered for both hot and cold water lines, holding pressure at temperatures where standard PVC fails. Solvent-cement jointed for leak-free runs.</p>`,
    highlights: ['Rated to 93°C continuous', 'Corrosion and scale resistant', 'Solvent cement jointing'],
    features: [
      { key: 'Material', value: 'CPVC (Chlorinated PVC)' },
      { key: 'Diameter', value: '1 inch (25 mm)' },
      { key: 'Length', value: '3 metres' },
      { key: 'Pressure Rating', value: 'SDR 11' },
      { key: 'Max Temperature', value: '93°C' },
      { key: 'Standard', value: 'ASTM D2846' },
      { key: 'Applications', value: 'Hot & Cold Water Supply, Geyser Lines' },
    ],
    images: [img('1581094794329-c8112a89af12', 'Plumbing pipes')],
    tags: ['cpvc', 'pipe', 'plumbing'],
  },
];

module.exports = { categories, brands, banners, coupons, products };
