module.exports = {
  User: require('./User'),
  Session: require('./Session'),
  Category: require('./Category'),
  SubCategory: require('./SubCategory'),
  Brand: require('./Brand'),
  Product: require('./Product'),
  ProductVariant: require('./ProductVariant'),
  Address: require('./Address'),
  Cart: require('./Cart'),
  Wishlist: require('./Wishlist'),
  Coupon: require('./Coupon'),
  Review: require('./Review'),
  Banner: require('./Banner'),
  Order: require('./Order'),
  Payment: require('./Payment'),
  Setting: require('./Setting'),
  Inquiry: require('./Inquiry'),
  NewsletterSubscriber: require('./NewsletterSubscriber'),
  JobPosition: require('./JobPosition'),
  JobApplication: require('./JobApplication'),
};
